import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SEGMENT_PATH_KEY } from "next/dist/server/lib/router-utils/build-prefetch-segment-data-route";
import { SettingsProvider } from "./components/setting/SettingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SettingsProvider>
        {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
